Update README and add "Now playing" Command
codetheweb/muse pull request #589
Opened 2022-03-18 16:53 UTC by Zagrthos

Closes #579

Changes werde made to the README File to include the LTS Version of Node.js and a command to run the bot 24/7 in background if you're using a server.

Closes #588

And added a "Now Playing" Slash Command that just shows the Embed from the first /play command to show what currently is played.

2022-03-18 23:57 UTC, codetheweb requested changes
Please keep different changes in separate PRs in the future.

I left a comment in https://github.com/codetheweb/muse/issues/588.

2022-03-18 23:57 UTC, codetheweb commented on README.md
> +* Node.js 16.x (16.x is recommended because of LTS. 17.x seems to make problems)
```suggestion
* Node.js (16.x is recommended because it's the current LTS version)
```

2022-03-18 23:57 UTC, codetheweb commented on README.md
> +	* `(npm run start&)` to run the bot 24/7 on a server
```suggestion

```

There's a lot of ways to run this on a server besides just as a background process, like [PM2](https://pm2.keymetrics.io/). I'd rather not recommend anything specific here.

2022-03-19 00:07 UTC, Zagrthos commented
Sorry! Initially I wanted to keep the changed separate but GitHub decided to merge them in one PR. Guess I create extra branches in the future for single changes to avoid this.

2022-03-19 00:24 UTC, codetheweb approved these changes
I made a few tweaks, if it looks good to you I'll go ahead and merge. :)

2022-03-19 12:04 UTC, Zagrthos commented
Already approved it! :)

2022-03-19 14:55 UTC, merged