Made error message format consistent
codetheweb/muse pull request #591
Opened 2022-03-19 10:43 UTC by therithwikrayani

Closes #590

Made error message format consistent

- [ ] I updated the changelog

2022-03-19 14:57 UTC, codetheweb requested changes
I'd like to keep the `ope` prefix. :)

Are there any other spots to your knowledge that would have to be changed too?

2022-03-19 14:57 UTC, codetheweb commented on src/utils/error-msg.ts
> +      str = `🚫 ${error.message}`;
```suggestion
      str = `🚫 ope: ${error.message}`;
```

2022-03-19 14:57 UTC, codetheweb commented on src/utils/error-msg.ts
>        str = `🚫 ${error}`;
```suggestion
      str = `🚫 ope: ${error}`;
```

2022-03-23 12:06 UTC, therithwikrayani commented
Very well, done as suggested

2022-03-23 12:07 UTC, therithwikrayani commented
No errors are thrown without using `error-msg.ts`, so shouldn't have to make changes anywhere else.

2022-03-23 23:28 UTC, codetheweb commented
Thanks!

2022-03-23 23:28 UTC, merged